(define (problem dumber-than-dirt)
    (:domain bulldozer)
  (:objects a g
        jack bulldozer)
  (:init (at jack a) (at bulldozer a)
     (vehicle bulldozer)
     (mobile jack)
     (person jack)
     (road a g))
  (:goal (AND (at bulldozer g)))
  )
