(define (problem three-way)
    (:domain three-way)
    (:objects top-station docks airport city quarry suburbs village depot thomas fat-controller quarry-stone coal)
    (:init (base top-station)
        (linked top-station city)
        (linked city docks)
        (linked docks quarry)
        (linked quarry top-station)
        (inService thomas top-station)
        (at fat-controller city)
        (at coal docks)
        (at quarry-stone quarry))
    (:goal (and (at fat-controller top-station)
            (at quarry-stone docks)
            (refuelling thomas)))
)
